builds:
  - binary: '{{ .ProjectName }}_v{{ .Version }}'
    main: ./cmd/github-team-approver
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - '-d -s -w '
    goos:
      - darwin
      - linux
    goarch:
      - '386'
      - amd64
      - arm
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
release:
  prerelease: auto
