version: 1.0
provider:
  name: openfaas
functions:
  github-team-approver:
    lang: golang-http
    handler: ./github-team-approver
    image: "${DOCKER_IMG}:${DOCKER_TAG}"
    labels:
      com.openfaas.scale.max: "${MAX_REPLICAS}"
      com.openfaas.scale.min: "${MIN_REPLICAS}"
      uid: ""
    environment:
      APP_NAME: "${APP_NAME}"
      GITHUB_APP_ID: "${GITHUB_APP_ID}"
      GITHUB_APP_INSTALLATION_ID: "${GITHUB_APP_INSTALLATION_ID}"
      GITHUB_APP_PRIVATE_KEY_PATH: /var/openfaas/secrets/github-team-approver-private-key
      GITHUB_APP_WEBHOOK_SECRET_TOKEN_PATH: /var/openfaas/secrets/github-team-approver-webhook-secret-token
      IGNORED_REPOSITORIES: "${IGNORED_REPOSITORIES}"
      LOG_LEVEL: "${LOG_LEVEL}"
      LOGZIO_TOKEN_PATH: /var/openfaas/secrets/github-team-approver-logzio-token
      STATUS_NAME: "${STATUS_NAME}"
      USE_CACHING_TRANSPORT: true
      read_timeout: "10s"
      write_timeout: "10s"
    secrets:
    - github-team-approver-private-key
    - github-team-approver-webhook-secret-token
    - github-team-approver-logzio-token
