[[constraint]]
  name = "github.com/google/go-github"
  version = "v28.0.0"

[[constraint]]
  name = "github.com/form3tech-oss/go-pact-testing"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/gregjones/httpcache"
  revision = "85712625ba05e3ca4d24006116eb36c40f2a504a"
  source = "github.com/form3tech-oss/httpcache"

[[constraint]]
  name = "github.com/form3tech-oss/github-team-approver-commons"
  version = "v1.0.0"

[prune]
  go-tests = true
  unused-packages = true
