on:
  pull_request:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Setup Go
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
        with:
          go-version-file: go.mod
      - run: make goimports
      - name: Test
        run: make test
  deploy:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Install Skaffold
        run: make install-skaffold
      - name: Skaffold push
        run: make skaffold.push
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          TAG: ${{ github.ref_name }}
